name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run:  |
          echo "job done1"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo
        run: |
          echo "job done2"
  job3:
    runs-on: ubuntu-latest
    needs: [ job2 ]
    steps:
      - name: echo
        run: |
          ec  ho "job done3"