name: ci.yml
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend : 
              - 'front/**'

    outputs:
      frontend: ${{steps.changes.outputs.frontend}}

  test:
    needs: detect-changes
    if: (github.event.action == 'opened' || github.event.action == 'synchronize') && needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name : 테스트
        run : |
         cd front && npm ci

  build:
    needs: detect-changes
    if: github.event_name == 'push' && needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: 빌드
        run: |
          cd front && npm run build
     
        

