name: 스테이징 반영

on:
  push:
    branches:
      - dev


  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: 체크아웃
          uses: actions/checkout@v4

        - name: 테스트
          run: |
            cd front && npm ci